version: '2'
volumes:
  mysql_data:
 
services:
# angular-js
  web:
    image: integritas/ui
    hostname: web
    expose:
    - "80"
    ports:
    - "80:80"
    depends_on:
    - api
# api-rest
  api:
    image: integritas/api
    hostname: api
    expose:
    - "8090"
    ports:
    - "8090:8090"
    links:
    - "shopping"
    - "payment"
    - "activemq"
    - "db-mysql"
    depends_on:
    - shopping
    - payment
    - activemq
    - db-mysql
# Microservices
  shopping:
    image: integritas/shopping
    hostname: shopping
    links:
    - "activemq"
    - "db-mysql"
    depends_on:
    - activemq
    - db-mysql
  payment:
    image: integritas/payment
    hostname: payment
    links:
    - "db-mysql"
    - "activemq"
    depends_on:
    - db-mysql
    - activemq
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
    - 8161:8161
    - 61616:61616
# Mysql
  db-mysql:
    image: mysql
    hostname: db-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: integritas
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"